{
 "title": "api dotnet 8",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average HTTP Request Duration",
   "type": "timeseries",
   "description": "Duração média das requisições HTTP nos últimos 5 minutos",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "{{method}} - {{endpoint}}"
    }
   ]
  },
  {
   "title": "Total HTTP Requests Received",
   "type": "bargauge",
   "description": "A métrica http_requests_received_total representa o número total de requisições HTTP recebidas pela aplicação. Esta métrica é um contador que aumenta à medida que novas requisições são recebidas, permitindo monitorar o volume de tráfego e analisar padrões de uso ao longo do tempo.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_received_total{job=\"my_dotnet_api\"}",
     "legendFormat": "{{method}} - {{endpoint}}"
    }
   ]
  },
  {
   "title": "CPU Usage Over Time",
   "type": "timeseries",
   "description": "Este painel mostra o uso total de CPU pelo processo ao longo do tempo, medido em segundos.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"my_dotnet_api\"}",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "timeseries",
   "description": "Este painel mostra o uso atual da CPU pela aplicação, medido em porcentagem. É útil para monitorar o uso instantâneo da CPU e garantir que a aplicação não está sobrecarregando o sistema.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{job=\"my_dotnet_api\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Contagem de Requisições por Status de Resposta",
   "type": "timeseries",
   "description": "Este painel exibe a contagem de requisições HTTP agrupadas por código de resposta, permitindo monitorar a distribuição dos status de resposta ao longo do tempo.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(code) (rate(http_request_duration_seconds_count{job=\"my_dotnet_api\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de Coletas de Lixo (GC) por Geração",
   "type": "timeseries",
   "description": "Este gráfico mostra a taxa de coletas de lixo (GC) por geração nos últimos 5 minutos, permitindo monitorar a frequência das coletas de lixo no sistema. Cada linha representa uma geração diferente, facilitando a comparação entre elas.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "dotnet_collection_count_total{job=\"my_dotnet_api\"}",
     "legendFormat": "{{generation}} - {{job}}"
    }
   ]
  }
 ]
}