apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: criar-contatos-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default  # ou "managed-premium", dependendo do seu cluster
