apiVersion: v1
kind: PersistentVolume
metadata:
  name: criar-contatos-persistent-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: /data/criar-contatos