apiVersion: v1
kind: PersistentVolume
metadata:
  name: producer-criar-contatos-persistent-volume
  labels:
    app: producer-criar-contatos
    tier: backend
  annotations:
    description: "Volume persistente para dados do microsserviço producer-criar-contatos"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: /data/producer-criar-contatos/logs/producer
