name: .NET CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore Producer/CreateContact/CriarContatos.Api.sln

      - name: Build
        run: dotnet build Producer/CreateContact/CriarContatos.Api.sln --configuration Release

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            Producer/CreateContact/CriarContatos.Test/bin/Release/net8.0/
            Producer/CreateContact/CriarContatos.Api/bin/Release/net8.0/

  test-and-api:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Start RabbitMQ
        run: |
          docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management
          for i in {1..10}; do
            if curl -f http://localhost:15672 > /dev/null 2>&1; then
              echo "RabbitMQ is running"
              exit 0
            fi
            echo "Waiting for RabbitMQ..."
            sleep 3
          done
          echo "RabbitMQ failed to start"
          exit 1

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Start API in Background
        env:
          ASPNETCORE_URLS: http://localhost:5102
        run: |
          cd CriarContatos.Api/bin/Release/net8.0/
          dotnet CriarContatos.Api.dll &
          for i in {1..10}; do
            if curl -f http://localhost:5102/health > /dev/null 2>&1; then
              echo "API started successfully"
              exit 0
            fi
            echo "Waiting for API to start..."
            sleep 3
          done
          echo "API failed to start"
          exit 1

      - name: Run Unit Tests
        run: dotnet test Producer/CreateContact/CriarContatos.Test/CriarContatos.Test.csproj --configuration Release --logger "trx;LogFileName=TestResults/unit-test-results.trx" --results-directory CriarContatos.Test/TestResults

      - name: Publish Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: CriarContatos.Test/TestResults

  setup-monitoring:
    runs-on: ubuntu-latest
    needs: test-and-api
    steps:
      - name: Get Host IP
        run: echo "HOST_IP=$(hostname -I | awk '{print $1}')" >> $GITHUB_ENV

      - name: Setup Prometheus
        run: |
          mkdir -p prometheus
          echo "
          global:
            scrape_interval: 5s
          scrape_configs:
            - job_name: 'dotnet-api'
              metrics_path: '/metrics'
              static_configs:
                - targets: ['${{ env.HOST_IP }}:5102']
          " > prometheus/prometheus.yml

          docker run -d --name prometheus -p 9090:9090 -v $(pwd)/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus

      - name: Setup Grafana
        run: docker run -d --name grafana -p 3000:3000 grafana/grafana

      - name: Wait for Prometheus
        run: |
          for i in {1..10}; do
            if curl -f http://localhost:9090/-/ready > /dev/null 2>&1; then
              echo "Prometheus is ready"
              exit 0
            fi
            echo "Waiting for Prometheus..."
            sleep 3
          done
          echo "Prometheus failed to start"
          exit 1

      - name: Verify Prometheus Metrics
        run: curl -s http://localhost:9090/api/v1/targets | jq -e '.data.activeTargets[] | select(.health == "up")'

      - name: Verify Grafana
        run: curl -L -f http://localhost:3000 > /dev/null || exit 1

  cleanup:
    runs-on: ubuntu-latest
    needs: [test-and-api, setup-monitoring]
    if: always()
    steps:
      - name: Cleanup Docker containers
        run: docker rm -f rabbitmq prometheus grafana || true
