name: .NET CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main

permissions:
  id-token: write  # Permissões para gerar o id-token

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore CriarContatos.Api.sln

      - name: Build
        run: dotnet build CriarContatos.Api.sln --configuration Release

      - name: Start RabbitMQ
        run: |
          docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management
          sleep 10
          for i in {1..10}; do
            if curl -u guest:guest -f http://localhost:15672/api/healthchecks/node > /dev/null 2>&1; then
              echo "RabbitMQ is ready"
              exit 0
            fi
            echo "Waiting for RabbitMQ to start... Attempt $i of 10"
            sleep 5
          done
          echo "RabbitMQ failed to start"
          exit 1

      - name: Set Environment Variables
        run: |
          echo "RABBITMQSETTINGS__HOST=localhost" >> $GITHUB_ENV
          echo "RABBITMQSETTINGS__USERNAME=guest" >> $GITHUB_ENV
          echo "RABBITMQSETTINGS__PASSWORD=guest" >> $GITHUB_ENV

      - name: Start API in Background
        env:
          ASPNETCORE_URLS: http://localhost:5102
        run: |
          cd CriarContatos.Api/bin/Release/net8.0/
          dotnet CriarContatos.Api.dll & disown
          sleep 5

      - name: Wait for API to Start
        run: |
          for i in {1..10}; do
            if curl -f http://localhost:5102/health > /dev/null 2>&1; then
              echo "API started successfully"
              exit 0
            fi
            echo "Waiting for API to start... Attempt $i of 10"
            sleep 3
          done
          echo "API failed to start"
          exit 1

      - name: Test API Health
        run: curl -f http://localhost:5102/health || exit 1

      - name: Test API Metrics
        run: curl -f http://localhost:5102/metrics || exit 1

      - name: Run Unit Tests        
        run: dotnet test CriarContatos.Test/CriarContatos.Test.csproj --configuration Release --logger "console;verbosity=detailed"

      - name: Publish
        run: dotnet publish CriarContatos.Api/CriarContatos.Api.csproj --configuration Release --output CriarContatos.Api/publish

      # --- Adicionando as etapas de Docker, ACR e AKS ---
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: d8474ed9-45a6-4b74-9ccd-a0fe6f5c421f
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: 6837c849-6303-4e99-a99f-316f98266202

      - name: Log in to Azure CLI (Using Managed Identity)
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Verificar se o cluster Kubernetes está acessível
        run: |
          if kubectl cluster-info; then
            echo "Cluster Kubernetes está acessível"
          else
            echo "Falha ao acessar o cluster Kubernetes"
            exit 1
          fi

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/criar-contatos:${{ github.sha }} -f CriarContatos.Api/Dockerfile .

      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/criar-contatos:${{ github.sha }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.AKS_RESOURCE_GROUP }}'
          cluster-name: '${{ secrets.AKS_CLUSTER_NAME }}'

      - name: Update Kubernetes Resources
        run: |
          # Deleta os recursos existentes, se houver
          kubectl delete service criar-contatos-service || true
          kubectl delete deployment criar-contatos-deployment || true
          kubectl delete pvc criar-contatos-persistent-volume-claim || true
          kubectl delete pv criar-contatos-persistent-volume || true

          # Aplica ConfigMap (cria ou atualiza se necessário)
          kubectl apply -f CriarContatos.Api/k8s/criar-contatos-configmap.yml

          # Aplica Deployment (cria ou atualiza se necessário)
          kubectl apply -f CriarContatos.Api/k8s/criar-contatos-deployment.yml

          # Aplica PVC e PV novos, caso necessário
          kubectl apply -f CriarContatos.Api/k8s/criar-contatos-persistent-volume.yml
          kubectl apply -f CriarContatos.Api/k8s/criar-contatos-persistent-volume-claim.yml

          # Aplica Service (cria ou atualiza se necessário)
          kubectl apply -f CriarContatos.Api/k8s/criar-contatos-service.yml

          # Espera o rollout do Deployment para garantir que a atualização foi bem-sucedida
          kubectl rollout status deployment/criar-contatos-deployment
      
      - name: Update AKS Deployment with new image
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            CriarContatos.Api/k8s/criar-contatos-deployment.yml
            CriarContatos.Api/k8s/criar-contatos-service.yml
          images: |
            ${{ secrets.ACR_LOGIN_SERVER }}/criar-contato:${{ github.sha }}
          imagepullsecrets: |
            acr-auth

      - name: Cleanup
        if: always()
        run: |
          docker rm -f rabbitmq || true
          docker volume prune -f
