name: .NET CI Pipeline

on:
  push:
    branches:
      - main
      - develop # Permite rodar a pipeline na develop
      - feature/* # Permite rodar em qualquer branch feature
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore CreateContactMicroservice/CriarContatos.Api.sln

    - name: Clean build directories
      run: dotnet clean CreateContactMicroservice/CriarContatos.Api.sln

    - name: Build
      run: dotnet build CreateContactMicroservice/CriarContatos.Api.sln --no-restore --configuration Release

    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: CreateContactMicroservice/**/bin/Release/net8.0/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: CreateContactMicroservice/

    - name: Run all tests
      run: dotnet test CreateContactMicroservice/CriarContatos.Api.sln --no-build --configuration Release --logger "trx;LogFileName=TestResults/test-results.trx"

    - name: List Test Results
      run: ls CreateContactMicroservice/CriarContatos.Test/TestResults || echo "Nenhum resultado encontrado."

    - name: Publish Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: CreateContactMicroservice/CriarContatos.Test/TestResults
