name: .NET CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build-and-restore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore CriarContatos.Api.sln

      - name: Build
        run: dotnet build CriarContatos.Api.sln --configuration Release

      # 🔹 Compacta arquivos antes de salvar como artifact
      - name: Compress Artifacts
        run: tar -czf build-artifacts.tar.gz CriarContatos.Test/bin/Release/net8.0/ CriarContatos.Api/bin/Release/net8.0/

      - name: Publish Compressed Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build-artifacts.tar.gz

  start-rabbitmq-and-api:
    runs-on: ubuntu-latest
    needs: build-and-restore
    steps:
      - name: Start RabbitMQ
        run: |
          docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management
          sleep 10 # Aguarda RabbitMQ subir

      - name: Verify RabbitMQ
        run: curl -f http://localhost:15672 || exit 1

      - uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./

      - name: Extract Artifacts
        run: tar -xzf build-artifacts.tar.gz

      - name: Start API in Background
        env:
          ASPNETCORE_URLS: http://localhost:5102
        run: |
          cd CriarContatos.Api/bin/Release/net8.0/
          dotnet CriarContatos.Api.dll &
          for i in {1..10}; do
            if curl -f http://localhost:5102/health > /dev/null 2>&1; then
              echo "API started successfully"
              exit 0
            fi
            echo "Waiting for API to start... Attempt $i of 10"
            sleep 3
          done
          echo "API failed to start after 10 attempts"
          exit 1

  unit-tests:
    runs-on: ubuntu-latest
    needs: start-rabbitmq-and-api
    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Tests
        run: dotnet test CriarContatos.Test/CriarContatos.Test.csproj --configuration Release --logger "trx;LogFileName=TestResults/unit-test-results.trx" --results-directory CriarContatos.Test/TestResults

      - name: Publish Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: CriarContatos.Test/TestResults

  cleanup-artifacts:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Delete old artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: build-artifacts

  cleanup:
    runs-on: ubuntu-latest
    needs: [unit-tests, cleanup-artifacts]
    if: always()
    steps:
      - name: Cleanup Docker containers
        run: |
          docker rm -f rabbitmq || true
          docker volume prune -f
